### ISSUE TITLE
What about parser's compatiblity switches

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop-ast#10]
Parser has a few ways to emit things that have changed with time: https://github.com/whitequark/parser/#usage

I believe we don't turn any of these on.

I ask the question before v1: should we turn them on (and risk breaking some cops) or keep the compatibility mode like this (until at least v2).

Note that currently there's no way that I know of to use `ruby-parse` to output the same ast.

```sh
$ ruby-parse -e "{}[1] = 2"
(indexasgn
  (hash)
  (int 1)
  (int 2))

$ ruby-parse -e "->{}"
(block
  (lambda)
  (args) nil)
```

Within RuboCop, it is:
```
(send
  (hash)
  :[]=
  (int 1)
  (int 2)
)

(block
  (send nil :lambda)
  (args) nil)
```

I haven't spend much time thinking about it, but at first sight the current mode is typically simpler and doesn't make a distinction between very similar things (e.g. `do |x, |` vs `do |x|`, or `->{}` vs `lambda {}`), which is typically what cop writers want. OTOH, if they need to distinguish these (e.g. writing a cop against  `|x, |`), then `NodePattern` is not sufficient and they will have to check the `loc` or `source` themselves.

If we decide *not* to change, I'll make a PR so that there's a switch for `ruby-parse` to output the same as `RuboCop`'s.

If we *do* decide to change, well, we should definitely do it before 1.0 as this might impact cops, as well as existing metrics (e.g. `->{}` is not an actual `:send` so ABC metric is not quite correct)

@rubocop-hq/rubocop-core what say you?

Related to https://github.com/rubocop-hq/rubocop/issues/5999

**Comment by marcandre** [comment]
`ruby-parse` now has `--legacy` switch.

Has anyone every complained that rubocop uses the legacy AST output? There's just a few failures of `rubocop-ast`, so it might be helpful to support both modes. For RuboCop there are a lot of failures because Commissioner is missing a few hooks. I'm curious to know how many failures there would be if these were added. I'm still leaning on keeping the legacy mode for RuboCop, for compatiblity and simplicity.

**Comment by bbatsov** [comment]
> Has anyone every complained that rubocop uses the legacy AST output?

Don't recall any complaints. Frankly, it seems I've missed myself those changes to `parser`. :-) I guess we can't drop support for the legacy mode without breaking all extensions, but it'd be nice if at least the main gem used whatever's considered the modern/proper AST format.
