### ISSUE TITLE
rubocop-ast-0.4.0 has broken Layout/LineLength

### ISSUE THREAD

**Issue by jonnynux** [rubocop-hq/rubocop-ast#113]
With the latest version of the gem I receive the following error when executing rubocop:
`An error occurred while Layout/LineLength cop was inspecting /home/jonny/Programming/myapp/app/workers/bot.rb:330:8.`

**Comment by peterberkenbosch** [comment]
confirming! Also see https://github.com/rubocop-hq/rubocop/issues/8713

**Comment by peterberkenbosch** [comment]
@jonnynux I had to update rubocop to `0.90.0`. That fixes this problem.

**Comment by jonnynux** [comment]
Yes, it works great.

**Comment by marcandre** [comment]
Sorry for this. Yes, 0.4.0 is compatible with 0.89.0+ only.

Let's keep this issue open, I should introduce a way for the main gem to know this and at least warn...
