### ISSUE TITLE
attribute_accessor? is too eager

### ISSUE THREAD

**Issue by fsateler** [rubocop-hq/rubocop-ast#12]
It will capture calls without parameters:

```ruby
RuboCop::ProcessedSource.new('do_something_with attr, asdf', RUBY_VERSION.to_f).ast.children[2].attribute_accessor? # => [:attr, []]
```

I suspect the pattern should be changed to something like:

```
(send nil? ${:attr_reader :attr_writer :attr_accessor :attr} $({sym str} _)+)
```

**Comment by marcandre** [comment]
Thanks for the issue. I agree we could not match it.

Your proposed pattern is too restrictive though; `attr call_method, *or_splat` for example.

I'll tweak it
