### ISSUE TITLE
Changelog link is a 404

### ISSUE THREAD

**Issue by tas50** [rubocop-hq/rubocop-ast#125]
The complete rewrite link at https://github.com/rubocop-hq/rubocop-ast/blob/master/CHANGELOG.md#new-features links to https://docs.rubocop.org/rubocop-ast/node_pattern_compiler.html, which is a 404

**Comment by marcandre** [comment]
Oh, thanks for opening the issue.
I actually don't even know how or if I have access to update the docs 😅. @bbatsov will probably do it soon, but in the meantime I'll change the link to the [source](https://github.com/rubocop-hq/rubocop-ast/blob/master/docs/modules/ROOT/pages/node_pattern_compiler.adoc)

**Comment by bbatsov** [comment]
I've pushed an update to the docs. Btw, everyone on the team can do this as well - that's the repo https://github.com/rubocop-hq/docs.rubocop.org, the README has all the instructions.

**Comment by marcandre** [comment]
Thanks (and now I know 😄 )
