### ISSUE TITLE
NodePattern for numblock "count" element

### ISSUE THREAD

**Issue by dvandersluis** [rubocop-hq/rubocop-ast#156]
Consider:

```shell
ruby-parse --27 -e "something { _1 }"
(numblock
  (send nil :something) 1
  (lvar :_1))
```

The count of numbered parameters is returned as a bare integer, which makes it extra resistant to being captured in a node pattern. It's not an `int` node so `int` or `int_type?` don't work, and if I try `#is_a?(Integer)` I get `ArgumentError: wrong number of arguments (given 2, expected 1)` for some reason.

Any suggestions?

**Comment by dvandersluis** [comment]
`#integer?` works if only using numblocks, but will fail when mixed with regular blocks:


```
({block numblock} _recv {(args ...) #integer?}
#=> NoMethodError: undefined method `integer?' for ...
```

**Comment by marcandre** [comment]
A precise example of what you are trying to achieve would help me.

You can use `%Integer` as a matcher, since `Integer===(val)` corresponds to `val.is_a?(Integer)`

**Comment by marcandre** [comment]
You can also use `is_a?(%Integer)`

What is confusing is that `Integer` or `int` are both interpreted the same way currently, and are compiled to `Integer_type?` and `int_type?`. The former doesn't make much sense...

**Comment by dvandersluis** [comment]
`%Integer` worked! Thanks!

This is the matcher, for rubocop#9127

```ruby
def_node_matcher :symbol_proc?, <<~PATTERN
  ({block numblock}
    ${(send ...) (super ...) zsuper}
    ${(args (arg _)) %Integer}
    (send (lvar _var) $_))
PATTERN
```

**Comment by marcandre** [comment]
Good. The question remains: should the `%` in front of the constant be necessary, and I'd be tempted to say no. OTOH the fact that `Const` or `%Const` would be the same is a bit ugly too...

**Comment by dvandersluis** [comment]
I agree, allowing `Const` makes sense to me, even if it introduces the small ugliness.
