### ISSUE TITLE
Document the Node extensions

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop-ast#17]
At the very minimum we need some page similar to that one https://docs.rubocop.org/rubocop-ast/node_pattern.html

We should probably mention somewhere in the docs that in effect this gem is an extension to the `ast` and `parser` gems. Right now users will certainly struggle to understand this, as our library overview is 5 lines long. :-)

**Comment by baweaver** [comment]
What do you mean by extensions here? Each of the node types themselves, or the general README for this gem?

**Comment by bbatsov** [comment]
> Each of the node types themselves

I meant each `ast` gem node type for which this gem provides some extensions. I was thinking that we should provide a bit of rationale for them and some code examples that are similar in spirit to the NodePattern docs.

**Comment by dorner** [comment]
Honestly, I just spent two days rootling around in the Ruby infrastructure trying to figure out a good way to parse things (I went past https://github.com/xinminlabs/synvert since it was way too obscure). I landed on this gem as the best way to do it, but I still have never found a description of all the different node types. For example, I just realized that `foo&.bar` is a `csend` type, while `foo.bar` is a `send` type.

It's kind of crazy that Rubocop (and `parser`!) has been under development for this long and no one has exhaustively written down what the node types are, let alone how to interact with them via `parser` and the Rubocoppy extensions. 😮

**Comment by dorner** [comment]
Oh - and some kind of sample code for how to rewrite things. :) For the record, after much inspection of the `parser` and `rubocop` gems, I landed on this:
```ruby
class Rule < Parser::AST::Processor
  include RuboCop::AST::Traversal

  def initialize(rewriter)
    @rewriter = rewriter
  end
end

    def process_rule(rule_class, code)
      ast_builder = RuboCop::AST::Builder.new
      parser = Parser::CurrentRuby.new(ast_builder)
      source_buffer = Parser::Source::Buffer.new('code')
      source_buffer.source = code
      node = parser.parse(source_buffer)
      rewriter = Parser::Source::TreeRewriter.new(source_buffer)
      rule = rule_class.new(rewriter)
      ([node] + node.descendants).each { |n| rule.process(n) }
      rewriter.process
    end
```
That's... a lot of setup to handle, but it works like a charm.

**Comment by marcandre** [comment]
> Honestly, I just spent two days rootling around in the Ruby infrastructure trying to figure out a good way to parse things (I went past https://github.com/xinminlabs/synvert since it was way too obscure). I landed on this gem as the best way to do it, but I still have never found a description of all the different node types. For example, I just realized that `foo&.bar` is a `csend` type, while `foo.bar` is a `send` type.

One good way to find out is typically to try it out with `ruby-parse --legacy -e "foo&.bar"`

> It's kind of crazy that Rubocop (and `parser`!) has been under development for this long and no one has exhaustively written down what the node types are, let alone how to interact with them via `parser` and the Rubocoppy extensions. 😮

There's definite space for good doc!

BTW parser has [pretty good documentation](https://github.com/whitequark/parser/blob/master/doc/AST_FORMAT.md) but the link could be made more obvious in their doc. 
If you use `rubocop-ast`, some of these AST nodes have special classes with extra methods. And yes, currently you have to look in the source...

**Comment by marcandre** [comment]
> Oh - and some kind of sample code for how to rewrite things. :) For the record, after much inspection of the `parser` and `rubocop` gems, I landed on this:
> 
> ```ruby
> class Rule < Parser::AST::Processor
>   include RuboCop::AST::Traversal
> 
>   def initialize(rewriter)
>     @rewriter = rewriter
>   end
> end
> 
>     def process_rule(rule_class, code)
>       ast_builder = RuboCop::AST::Builder.new
>       parser = Parser::CurrentRuby.new(ast_builder)
>       source_buffer = Parser::Source::Buffer.new('code')
>       source_buffer.source = code
>       node = parser.parse(source_buffer)
>       rewriter = Parser::Source::TreeRewriter.new(source_buffer)
>       rule = rule_class.new(rewriter)
>       ([node] + node.descendants).each { |n| rule.process(n) }
>       rewriter.process
>     end
> ```
> 
> That's... a lot of setup to handle, but it works like a charm.

Code looks good, I agree it would be nice to have a few higher level methods to do this quickly...

**Comment by dorner** [comment]
Wow, that page was nowhere when I was Googling! 😮 One thing is that it goes the other way - it maps Ruby features to node types, not the other way around.

Maybe next week I can try for some PR's to a) add some docs and b) add a utility class to make parsing / rewriting easier a la the pattern I'm using above - unless someone has a cleaner way to do it.
