### ISSUE TITLE
Missing patterns for Struct

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop-ast#28]
We need a `struct_constructor?` matcher (see #8122)
A more general "class_definition?` matcher that would match `class Foo < Bar`, `Struct.new(...) do` and `Class.new(...) do` would be nice too

**Comment by marcandre** [comment]
Maybe the same should be applied to `Module`s, and a very generic `module_creation?` that would encompass both classes (which are modules) and modules?

**Comment by bbatsov** [comment]
I like this idea, although we'll probably need something more specific for modules as well, as I don't recall many instances in RuboCop where we treated classes as modules.

**Comment by marcandre** [comment]
Right, I don't know the cops well enough, there might not be a need for a way to select "code blocks".
