### ISSUE TITLE
Setup coverage

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop-ast#3]

**Comment by marcandre** [comment]
@bbatsov I don't seem to have the necessary access to add `rubocop-ast` to codeclimate, could you do it for me please?

**Comment by bbatsov** [comment]
Done.

**Comment by marcandre** [comment]
Great. I can't set it coverage on code climate though (not authorized). Let me know how I can help. On my local machine, `COVERAGE=t bundle exec rake spec` seems to work fine now.

**Comment by bbatsov** [comment]
Seems only org admin can access CodeClimate. Let me "promote" you, as I guess that'd be easiest.

**Comment by bbatsov** [comment]
Try now again.

**Comment by marcandre** [comment]
Mmm, no, sorry, same "you don't have access" screen. I'm off to bed, let me know :-)

**Comment by marcandre** [comment]
Oh, I managed to re-sync my repos and it works now. Cool :-) I'll look at it tomorrow.

**Comment by bbatsov** [comment]
I had to do myself before seeing anything meaningful there, even if by default CodeClimate said that it had done some auto-sync a few minutes ago. Modern software... :D

**Comment by marcandre** [comment]
Odd, now `rubocop` itself has issues with coverage: https://circleci.com/gh/rubocop-hq/rubocop/109917
I won't be able to look at it until tonight (EST)

**Comment by bbatsov** [comment]
I think I broke and fixed this. In the CC settings the repo was still listed as my person repo and I deleted and recreated it, but forgot I needed to add CC_TEST_REPORTER_ID to the build environment in CircleCI.

**Comment by marcandre** [comment]
Done
