### ISSUE TITLE
on_index, on_indexasgn, on_lambda callbacks seem to be missing?

### ISSUE THREAD

**Issue by alfonsoperez** [rubocop-hq/rubocop-ast#43]
--------

## Expected behavior

Have callbacks available for https://github.com/whitequark/parser/commit/7d72eba571b8684ff452dd9c1885ea8c43698442 and `_type?`

## Actual behavior

Above callbacks don't seem to be called for appropiate nodes

## Steps to reproduce the problem

```
module RuboCop
  module Cop
    module Deprecation
       class MutatedStrings < Cop
           MSG = "Don't mutate strings!"
           
           def on_indexasgn(node)
              binding.pry
           end
        end
       end
    end
  end
end
```

And a quick test with:
```
  it 'register an offense when indexed assignment is being used on a string' do
    expect_offense(<<~RUBY)
      foo[1] = 'c'
    RUBY
 end
```

It appears that the callback is not being called, nor a `node` as `indexasgn_type?` available

## RuboCop version

```
$ rubocop -V
0.57.2 (using Parser 2.5.1.0, running on ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

I am fairly new to ruby and definitely to rubocop, so excuse the issue / vs potential PR, I would love to contribute with some tips!.

**Comment by marcandre** [comment]
Transferred to rubocop-ast. I'll handle it.
