### ISSUE TITLE
Parser and emit_forward_arg

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop-ast#44]
I'd like to use the latest version of parser with `emit_forward_arg` turned on.

We could avoid [this "hack" of redefining `to_a` as different from `children`](https://github.com/rubocop-hq/rubocop-ast/blob/master/lib/rubocop/ast/node/forward_args_node.rb#L13-L15)

```sh
$ ruby-parse --legacy-forward-arg -e "def foo(...);end; def bar(*rest); end"
(begin
  (def :foo
    (forward-args) nil)
  (def :bar
    (args
      (restarg :rest)) nil))

$ ruby-parse -e "def foo(...);end; def bar(*rest); end"
(begin
  (def :foo
    (args
      (forward-arg)) nil)
  (def :bar
    (args
      (restarg :rest)) nil))
```

The later form is much improved as an argument signature is always inside an `args` node.

I doubt it would be much incompatibility, but v1 would be perfect for this.

Comments / objections?

**Comment by bbatsov** [comment]
Fine by me.
