### ISSUE TITLE
Automate the release process with a rake task

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop-ast#67]
I'm suggesting this mostly because I've noticed in the previous release we forgot to set the docs version in `antora.yml`. In RuboCop itself the `cut_release` task does all such updates automatically.

**Comment by marcandre** [comment]
I copied that task, I guess it just needs to be adapted for the new docs

**Comment by marcandre** [comment]
Is [resetting the version](https://github.com/rubocop-hq/rubocop/commit/804c8e6af7f51fd4717e64a3a7980114466acb95) mandatory?
