### ISSUE TITLE
Incomplete tuple matching

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rubocop-ast#79]
This is more of a question than a feature request.
In [`rubocop-rspec`](https://github.com/rubocop-hq/rubocop-rspec)'s cops there are two patterns have redundancy.

1. [`RSpec/SubjectStub`](https://github.com/rubocop-hq/rubocop-rspec/blob/6266a6a2abefc275558f7360148db32ef36e7443/lib/rubocop/cop/rspec/subject_stub.rb#L45)
```
{
  (block (send nil? :subject (sym $_)) ...)
  (block (send nil? $:subject) ...)
}
```

It is supposed to capture `:subject` or the subject's name from:
```ruby
subject { ... }
# or
subject(:name) { ... }
```

What makes me think it's redundant?
 - an equal number of captures
 - same wrapping, e.g. base of the tree is the same

What makes it impossible to turn this into:
```
(block
  (send nil?
    {
      :subject (sym $_)
      $:subject
    }
  )
  ...
)
```
is that `{}` would consider all three expressions as matching options, and there is no way (that I'm aware of) to match two or more subsequent nodes that do not compose a complete sequence (terminology may be distorted, hope the idea is clear though).

2. The same applies to another cop, `RSpec/DescribeClass`:
```
          (block
            [  (send #{RSPEC} :describe $[!const !#string_constant?] ...)
              !(send #{RSPEC} :describe ... (hash <#rails_metadata? ...>)) ]
            ...
          )
```
It can't be:
```
(block
  (send #{RSPEC} :describe
    [
      $[!const !#string_constant?] ...
      ... !(hash <#rails_metadata? ...>)
    ]
  )
  ...
)
```
because there's no way to combine those (newline-separated) elements into tuples.

I would really prefer to keep Node Pattern syntax simple. And, unlike the previously introduced unordered sequence (`<>`) there's much of a compelling benefit since I could only find two cops that would just slightly (and arguably) benefit from that.

On the other hand, `<>` is present already, but it disregards the order. Maybe it's possible somehow to respect the order given some specifier?
Not a real proposal, just thinking aloud:
```
(block (send nil? { <- :subject (sym $_)> $:subject } ) ... )
```
(`Couldn't compile due to invalid token "<".`)

```
(block
  (send #{RSPEC} :describe
     <- $[!const !#string_constant?] ...>
    !<- ... (hash <#rails_metadata? ...>)>
  ) ...)
```

where `<- >` is an "ordered sequence".

I didn't look much into RuboCop core's cops, can't estimate if any of them could benefit from such syntax.

**Comment by marcandre** [comment]
Yes, I was thinking about that the other day.

One way would be to extend the syntax in the following way:

`{ int int int | sym }` => a sequence of 3 ints or a single sym.
`{ int sym str }` would just be a shorthand for `{ int | sym | str }`

**Comment by pirj** [comment]
Ha, `{ | }` looks great 👍 

I don't insist on `[ | ]`, since:
 - there's just a single use case for it
 - I doubt that the following is even readable
```
(block
  (send #{RSPEC} :describe
     [$[!const !#string_constant?] ... | ... !(hash <#rails_metadata? ...>)]
  ) ...)
```

**Comment by marcandre** [comment]
Right. Does it actually require the outer `[]`? Can you call `RSpec.describe :directly => 'without first argument'`

```
(block
  (send #{RSPEC} :describe
     $[!const !#string_constant?] ... !(hash <#rails_metadata? ...>)
  ) ...)
```

**Comment by marcandre** [comment]
The only issue with `{ | }` is that it would require to go from the current recursive descent to having an actual AST first and then compiling it, I see no other way.

I kind of had to do that a bit with my `Compiler::Sequence` class that is kind of a hack, so I think the resulting code might even be nicer.

Other possibility would be to introduce a different notation, say `| int int int || sym |` instead of `{ int int int | sym }`

**Comment by pirj** [comment]
I would expect
```
(block
  (send #{RSPEC} :describe
     $[!const !#string_constant?] ... !(hash <#rails_metadata? ...>)
  ) ...)
```
to work, but it doesn't, as it doesn't match if there's no `hash` at all, but it should:
```ruby
describe 'class' do # Alarma! Should be camel case!
end
```

RSpec's legit syntax is very permissive in this regard, e.g.:
```ruby
describe 'Class', '#method', :symbol_metadata, hash_metadata: true do
  # ...
end
```

**Comment by pirj** [comment]
`{ int int int | sym }` looks best to me if you ask, and `{{ | }}` is not bad either.

I really don't want to push you for a major refactoring for a relatively rarely used feature. No rush. Consider this a crazy idea with intangible value on par with my other today's tickets.

**Comment by marcandre** [comment]
> to work, but it doesn't,

`(type x ... y) #=> children.size >= 2` for any `x` and `y`, even if `y` is `!<something>`.

**Comment by marcandre** [comment]
Done and released.

**Comment by pirj** [comment]
Thank you!
