### ISSUE TITLE
Publish docs to our docs portal (docs.rubocop.org)

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop-ast#9]
I'm wondering if we should publish some docs to RTD for the gem or keep things light. I'm guessing some documentation of the key concepts and the existing node extensions would be useful. Right now all we have is a section on NodePattern.

**Comment by marcandre** [comment]
I have the impression that the rest of the doc is in `rubocop`'s `development.md`. Maybe it's worth splitting the AST looking part from the rest?

**Comment by bbatsov** [comment]
Let's wait on this a bit. Yesterday I finally started moving the RuboCop docs to Antora (it uses AsciiDoc internally), and I want to finish this first before making any further changes. I've never really liked RTD, and I decided that RuboCop 1.0 deserves a better docs site. With Antora it will be natural to just have a documentation module for `rubocop-ast` that sits right in the main site (it can pull docs sources from multiple repos and combine the documentation together).

**Comment by bbatsov** [comment]
I migrated the gem's docs to our new docs site https://docs.rubocop.org/rubocop-ast/index.html 

Going forward you'll need to remember to update the version in `antora.yml` when cutting new releases, as failure to do so will break the docs publishing pipeline.

**Comment by marcandre** [comment]
Ok. I'll add some code in the cutting task to either add such a commit to `../rubocop` or warn if there's no such directly.

**Comment by marcandre** [comment]
Actually, couldn't this all be done automatically by a Github action somehow?

**Comment by bbatsov** [comment]
Maybe. I haven't played much with GitHub Actions yet - so far I've only used it for CI purposes.

**Comment by dorner** [comment]
@bbatsov I'm trying to add a pretty large document on node types and can't get Antora to work. I followed the instructions from the rubocop-docs repo and I get the following error:

```
[danielorner rubocop-ast (document-node-types)] npm i -g @antora/cli@2.0 @antora/site-generator-default@2.0
/Users/danielorner/.nvm/versions/node/v13.3.0/bin/antora -> /Users/danielorner/.nvm/versions/node/v13.3.0/lib/node_modules/@antora/cli/bin/antora
+ @antora/cli@2.0.1
+ @antora/site-generator-default@2.0.1
added 269 packages from 207 contributors in 21.269s
[danielorner rubocop-ast (document-node-types)] antora --pull docs/antora.yml 
error: ui.bundle.url: must be of type String
configuration param 'name' not declared in the schema
configuration param 'title' not declared in the schema
configuration param 'version' not declared in the schema
configuration param 'nav' not declared in the schema
Add the --stacktrace option to see the cause.
```

Any ideas?

**Comment by bbatsov** [comment]
@dorner You're running the command in the wrong repo - you should invoke it in `docs.rubocop.org` (the rubocop-docs repo).

**Comment by dorner** [comment]
Ah - didn't realize what the workflow was for this, thanks!

**Comment by bbatsov** [comment]
One more thing - you'll have to update the `antora-playbook.yml` to pull data from your branch, instead of from the upstream repo. I forgot to mention this in the docs.

**Comment by dorner** [comment]
Yeah we probably should add details on how to update documentation - looks like you need a PR here and then have to kick off the deploy in the docs repo? Or are there two PRs necessary?

**Comment by bbatsov** [comment]
I occasionally trigger the update of the docs in the second repo manually. At some point I'm hoping to automate the process using some cross-repo GitHub action, if possible.
